apiVersion: apps/v1

kind: "Deployment"
metadata:
  labels:
    app: "cmsnesia-admin"
    version: "1.0.0-SNAPSHOT"
    group: "com.cmsnesia.admin"
  name: "cmsnesia-admin-deployment"
  namespace: "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cmsnesia-admin-exposed"
      version: "1.0.0-SNAPSHOT"
      group: "com.cmsnesia.admin"
  template:
    metadata:
      labels:
        app: "cmsnesia-admin-exposed"
        version: "1.0.0-SNAPSHOT"
        group: "com.cmsnesia.admin"
    spec:
      containers:
        - env:
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: "NGINX_HOST"
              value: "admin.cmsnesia.com"
            - name: "NGINX_PORT"
              value: "80"
          name: "cmsnesia-admin"
          image: "ardikars/cmsnesia-admin:latest"
          ports:
            - containerPort: 80
              name: "http"
              protocol: "TCP"