apiVersion: v1

kind: "Service"
metadata:
  labels:
    app: "cmsnesia-admin"
    version: "1.0.0-SNAPSHOT"
    group: "com.cmsnesia.admin"
  name: "cmsnesia-admin-service"
  namespace: "default"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: "TCP"
      name: "http"
  selector:
    app: "cmsnesia-admin-exposed"
    version: "1.0.0-SNAPSHOT"
    group: "com.cmsnesia.admin"
  type: "LoadBalancer"
